# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/82805/CLionProjects/polytoria

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/82805/CLionProjects/polytoria

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /Users/82805/CLionProjects/polytoria && $(CMAKE_COMMAND) -E cmake_progress_start /Users/82805/CLionProjects/polytoria/CMakeFiles /Users/82805/CLionProjects/polytoria/vendor/vm//CMakeFiles/progress.marks
	cd /Users/82805/CLionProjects/polytoria && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vendor/vm/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/82805/CLionProjects/polytoria/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/82805/CLionProjects/polytoria && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vendor/vm/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/82805/CLionProjects/polytoria && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vendor/vm/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/82805/CLionProjects/polytoria && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vendor/vm/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/82805/CLionProjects/polytoria && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
vendor/vm/CMakeFiles/luajit.dir/rule:
	cd /Users/82805/CLionProjects/polytoria && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vendor/vm/CMakeFiles/luajit.dir/rule
.PHONY : vendor/vm/CMakeFiles/luajit.dir/rule

# Convenience name for target.
luajit: vendor/vm/CMakeFiles/luajit.dir/rule
.PHONY : luajit

# fast build rule for target.
luajit/fast:
	cd /Users/82805/CLionProjects/polytoria && $(MAKE) $(MAKESILENT) -f vendor/vm/CMakeFiles/luajit.dir/build.make vendor/vm/CMakeFiles/luajit.dir/build
.PHONY : luajit/fast

# Convenience name for target.
vendor/vm/CMakeFiles/vm.dir/rule:
	cd /Users/82805/CLionProjects/polytoria && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vendor/vm/CMakeFiles/vm.dir/rule
.PHONY : vendor/vm/CMakeFiles/vm.dir/rule

# Convenience name for target.
vm: vendor/vm/CMakeFiles/vm.dir/rule
.PHONY : vm

# fast build rule for target.
vm/fast:
	cd /Users/82805/CLionProjects/polytoria && $(MAKE) $(MAKESILENT) -f vendor/vm/CMakeFiles/vm.dir/build.make vendor/vm/CMakeFiles/vm.dir/build
.PHONY : vm/fast

src/allocator.o: src/allocator.c.o
.PHONY : src/allocator.o

# target to build an object file
src/allocator.c.o:
	cd /Users/82805/CLionProjects/polytoria && $(MAKE) $(MAKESILENT) -f vendor/vm/CMakeFiles/vm.dir/build.make vendor/vm/CMakeFiles/vm.dir/src/allocator.c.o
.PHONY : src/allocator.c.o

src/allocator.i: src/allocator.c.i
.PHONY : src/allocator.i

# target to preprocess a source file
src/allocator.c.i:
	cd /Users/82805/CLionProjects/polytoria && $(MAKE) $(MAKESILENT) -f vendor/vm/CMakeFiles/vm.dir/build.make vendor/vm/CMakeFiles/vm.dir/src/allocator.c.i
.PHONY : src/allocator.c.i

src/allocator.s: src/allocator.c.s
.PHONY : src/allocator.s

# target to generate assembly for a file
src/allocator.c.s:
	cd /Users/82805/CLionProjects/polytoria && $(MAKE) $(MAKESILENT) -f vendor/vm/CMakeFiles/vm.dir/build.make vendor/vm/CMakeFiles/vm.dir/src/allocator.c.s
.PHONY : src/allocator.c.s

src/bridge.o: src/bridge.c.o
.PHONY : src/bridge.o

# target to build an object file
src/bridge.c.o:
	cd /Users/82805/CLionProjects/polytoria && $(MAKE) $(MAKESILENT) -f vendor/vm/CMakeFiles/vm.dir/build.make vendor/vm/CMakeFiles/vm.dir/src/bridge.c.o
.PHONY : src/bridge.c.o

src/bridge.i: src/bridge.c.i
.PHONY : src/bridge.i

# target to preprocess a source file
src/bridge.c.i:
	cd /Users/82805/CLionProjects/polytoria && $(MAKE) $(MAKESILENT) -f vendor/vm/CMakeFiles/vm.dir/build.make vendor/vm/CMakeFiles/vm.dir/src/bridge.c.i
.PHONY : src/bridge.c.i

src/bridge.s: src/bridge.c.s
.PHONY : src/bridge.s

# target to generate assembly for a file
src/bridge.c.s:
	cd /Users/82805/CLionProjects/polytoria && $(MAKE) $(MAKESILENT) -f vendor/vm/CMakeFiles/vm.dir/build.make vendor/vm/CMakeFiles/vm.dir/src/bridge.c.s
.PHONY : src/bridge.c.s

src/platforms/macos.o: src/platforms/macos.c.o
.PHONY : src/platforms/macos.o

# target to build an object file
src/platforms/macos.c.o:
	cd /Users/82805/CLionProjects/polytoria && $(MAKE) $(MAKESILENT) -f vendor/vm/CMakeFiles/vm.dir/build.make vendor/vm/CMakeFiles/vm.dir/src/platforms/macos.c.o
.PHONY : src/platforms/macos.c.o

src/platforms/macos.i: src/platforms/macos.c.i
.PHONY : src/platforms/macos.i

# target to preprocess a source file
src/platforms/macos.c.i:
	cd /Users/82805/CLionProjects/polytoria && $(MAKE) $(MAKESILENT) -f vendor/vm/CMakeFiles/vm.dir/build.make vendor/vm/CMakeFiles/vm.dir/src/platforms/macos.c.i
.PHONY : src/platforms/macos.c.i

src/platforms/macos.s: src/platforms/macos.c.s
.PHONY : src/platforms/macos.s

# target to generate assembly for a file
src/platforms/macos.c.s:
	cd /Users/82805/CLionProjects/polytoria && $(MAKE) $(MAKESILENT) -f vendor/vm/CMakeFiles/vm.dir/build.make vendor/vm/CMakeFiles/vm.dir/src/platforms/macos.c.s
.PHONY : src/platforms/macos.c.s

src/sandbox.o: src/sandbox.c.o
.PHONY : src/sandbox.o

# target to build an object file
src/sandbox.c.o:
	cd /Users/82805/CLionProjects/polytoria && $(MAKE) $(MAKESILENT) -f vendor/vm/CMakeFiles/vm.dir/build.make vendor/vm/CMakeFiles/vm.dir/src/sandbox.c.o
.PHONY : src/sandbox.c.o

src/sandbox.i: src/sandbox.c.i
.PHONY : src/sandbox.i

# target to preprocess a source file
src/sandbox.c.i:
	cd /Users/82805/CLionProjects/polytoria && $(MAKE) $(MAKESILENT) -f vendor/vm/CMakeFiles/vm.dir/build.make vendor/vm/CMakeFiles/vm.dir/src/sandbox.c.i
.PHONY : src/sandbox.c.i

src/sandbox.s: src/sandbox.c.s
.PHONY : src/sandbox.s

# target to generate assembly for a file
src/sandbox.c.s:
	cd /Users/82805/CLionProjects/polytoria && $(MAKE) $(MAKESILENT) -f vendor/vm/CMakeFiles/vm.dir/build.make vendor/vm/CMakeFiles/vm.dir/src/sandbox.c.s
.PHONY : src/sandbox.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... luajit"
	@echo "... vm"
	@echo "... src/allocator.o"
	@echo "... src/allocator.i"
	@echo "... src/allocator.s"
	@echo "... src/bridge.o"
	@echo "... src/bridge.i"
	@echo "... src/bridge.s"
	@echo "... src/platforms/macos.o"
	@echo "... src/platforms/macos.i"
	@echo "... src/platforms/macos.s"
	@echo "... src/sandbox.o"
	@echo "... src/sandbox.i"
	@echo "... src/sandbox.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/82805/CLionProjects/polytoria && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

